/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BookRouteImport } from './routes/book'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SeoSlugRouteImport } from './routes/$seoSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceWelcomeBabyDecorationRouteImport } from './routes/service.welcome-baby-decoration'
import { Route as ServiceThemeBirthdayDecorationRouteImport } from './routes/service.theme-birthday-decoration'
import { Route as ServiceRomanticBedroomDecorationRouteImport } from './routes/service.romantic-bedroom-decoration'
import { Route as ServiceRiceCeremonyDecorationRouteImport } from './routes/service.rice-ceremony-decoration'
import { Route as ServiceProposalDecorationRouteImport } from './routes/service.proposal-decoration'
import { Route as ServiceMehendiDecorationRouteImport } from './routes/service.mehendi-decoration'
import { Route as ServiceKidsThemeDecorationRouteImport } from './routes/service.kids-theme-decoration'
import { Route as ServiceHousewarmingDecorationRouteImport } from './routes/service.housewarming-decoration'
import { Route as ServiceHaldiDecorationRouteImport } from './routes/service.haldi-decoration'
import { Route as ServiceEngagementDecorationRouteImport } from './routes/service.engagement-decoration'
import { Route as ServiceCorporateEventDecorationRouteImport } from './routes/service.corporate-event-decoration'
import { Route as ServiceCarBootDecorationRouteImport } from './routes/service.car-boot-decoration'
import { Route as ServiceBirthdayDecorationRouteImport } from './routes/service.birthday-decoration'
import { Route as ServiceBacheloretteDecorationRouteImport } from './routes/service.bachelorette-decoration'
import { Route as ServiceBabyShowerDecorationRouteImport } from './routes/service.baby-shower-decoration'
import { Route as ServiceAnniversaryDecorationRouteImport } from './routes/service.anniversary-decoration'
import { Route as PackageIdRouteImport } from './routes/package.$id'
import { Route as CitySlugRouteImport } from './routes/city.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoSlugRoute = SeoSlugRouteImport.update({
  id: '/$seoSlug',
  path: '/$seoSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceWelcomeBabyDecorationRoute =
  ServiceWelcomeBabyDecorationRouteImport.update({
    id: '/service/welcome-baby-decoration',
    path: '/service/welcome-baby-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceThemeBirthdayDecorationRoute =
  ServiceThemeBirthdayDecorationRouteImport.update({
    id: '/service/theme-birthday-decoration',
    path: '/service/theme-birthday-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceRomanticBedroomDecorationRoute =
  ServiceRomanticBedroomDecorationRouteImport.update({
    id: '/service/romantic-bedroom-decoration',
    path: '/service/romantic-bedroom-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceRiceCeremonyDecorationRoute =
  ServiceRiceCeremonyDecorationRouteImport.update({
    id: '/service/rice-ceremony-decoration',
    path: '/service/rice-ceremony-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceProposalDecorationRoute =
  ServiceProposalDecorationRouteImport.update({
    id: '/service/proposal-decoration',
    path: '/service/proposal-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceMehendiDecorationRoute =
  ServiceMehendiDecorationRouteImport.update({
    id: '/service/mehendi-decoration',
    path: '/service/mehendi-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceKidsThemeDecorationRoute =
  ServiceKidsThemeDecorationRouteImport.update({
    id: '/service/kids-theme-decoration',
    path: '/service/kids-theme-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceHousewarmingDecorationRoute =
  ServiceHousewarmingDecorationRouteImport.update({
    id: '/service/housewarming-decoration',
    path: '/service/housewarming-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceHaldiDecorationRoute = ServiceHaldiDecorationRouteImport.update({
  id: '/service/haldi-decoration',
  path: '/service/haldi-decoration',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceEngagementDecorationRoute =
  ServiceEngagementDecorationRouteImport.update({
    id: '/service/engagement-decoration',
    path: '/service/engagement-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceCorporateEventDecorationRoute =
  ServiceCorporateEventDecorationRouteImport.update({
    id: '/service/corporate-event-decoration',
    path: '/service/corporate-event-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceCarBootDecorationRoute =
  ServiceCarBootDecorationRouteImport.update({
    id: '/service/car-boot-decoration',
    path: '/service/car-boot-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceBirthdayDecorationRoute =
  ServiceBirthdayDecorationRouteImport.update({
    id: '/service/birthday-decoration',
    path: '/service/birthday-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceBacheloretteDecorationRoute =
  ServiceBacheloretteDecorationRouteImport.update({
    id: '/service/bachelorette-decoration',
    path: '/service/bachelorette-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceBabyShowerDecorationRoute =
  ServiceBabyShowerDecorationRouteImport.update({
    id: '/service/baby-shower-decoration',
    path: '/service/baby-shower-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServiceAnniversaryDecorationRoute =
  ServiceAnniversaryDecorationRouteImport.update({
    id: '/service/anniversary-decoration',
    path: '/service/anniversary-decoration',
    getParentRoute: () => rootRouteImport,
  } as any)
const PackageIdRoute = PackageIdRouteImport.update({
  id: '/package/$id',
  path: '/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CitySlugRoute = CitySlugRouteImport.update({
  id: '/city/$slug',
  path: '/city/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$seoSlug': typeof SeoSlugRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/packages': typeof PackagesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/package/$id': typeof PackageIdRoute
  '/service/anniversary-decoration': typeof ServiceAnniversaryDecorationRoute
  '/service/baby-shower-decoration': typeof ServiceBabyShowerDecorationRoute
  '/service/bachelorette-decoration': typeof ServiceBacheloretteDecorationRoute
  '/service/birthday-decoration': typeof ServiceBirthdayDecorationRoute
  '/service/car-boot-decoration': typeof ServiceCarBootDecorationRoute
  '/service/corporate-event-decoration': typeof ServiceCorporateEventDecorationRoute
  '/service/engagement-decoration': typeof ServiceEngagementDecorationRoute
  '/service/haldi-decoration': typeof ServiceHaldiDecorationRoute
  '/service/housewarming-decoration': typeof ServiceHousewarmingDecorationRoute
  '/service/kids-theme-decoration': typeof ServiceKidsThemeDecorationRoute
  '/service/mehendi-decoration': typeof ServiceMehendiDecorationRoute
  '/service/proposal-decoration': typeof ServiceProposalDecorationRoute
  '/service/rice-ceremony-decoration': typeof ServiceRiceCeremonyDecorationRoute
  '/service/romantic-bedroom-decoration': typeof ServiceRomanticBedroomDecorationRoute
  '/service/theme-birthday-decoration': typeof ServiceThemeBirthdayDecorationRoute
  '/service/welcome-baby-decoration': typeof ServiceWelcomeBabyDecorationRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$seoSlug': typeof SeoSlugRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/packages': typeof PackagesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/package/$id': typeof PackageIdRoute
  '/service/anniversary-decoration': typeof ServiceAnniversaryDecorationRoute
  '/service/baby-shower-decoration': typeof ServiceBabyShowerDecorationRoute
  '/service/bachelorette-decoration': typeof ServiceBacheloretteDecorationRoute
  '/service/birthday-decoration': typeof ServiceBirthdayDecorationRoute
  '/service/car-boot-decoration': typeof ServiceCarBootDecorationRoute
  '/service/corporate-event-decoration': typeof ServiceCorporateEventDecorationRoute
  '/service/engagement-decoration': typeof ServiceEngagementDecorationRoute
  '/service/haldi-decoration': typeof ServiceHaldiDecorationRoute
  '/service/housewarming-decoration': typeof ServiceHousewarmingDecorationRoute
  '/service/kids-theme-decoration': typeof ServiceKidsThemeDecorationRoute
  '/service/mehendi-decoration': typeof ServiceMehendiDecorationRoute
  '/service/proposal-decoration': typeof ServiceProposalDecorationRoute
  '/service/rice-ceremony-decoration': typeof ServiceRiceCeremonyDecorationRoute
  '/service/romantic-bedroom-decoration': typeof ServiceRomanticBedroomDecorationRoute
  '/service/theme-birthday-decoration': typeof ServiceThemeBirthdayDecorationRoute
  '/service/welcome-baby-decoration': typeof ServiceWelcomeBabyDecorationRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$seoSlug': typeof SeoSlugRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/mcp': typeof McpRoute
  '/packages': typeof PackagesRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/city/$slug': typeof CitySlugRoute
  '/package/$id': typeof PackageIdRoute
  '/service/anniversary-decoration': typeof ServiceAnniversaryDecorationRoute
  '/service/baby-shower-decoration': typeof ServiceBabyShowerDecorationRoute
  '/service/bachelorette-decoration': typeof ServiceBacheloretteDecorationRoute
  '/service/birthday-decoration': typeof ServiceBirthdayDecorationRoute
  '/service/car-boot-decoration': typeof ServiceCarBootDecorationRoute
  '/service/corporate-event-decoration': typeof ServiceCorporateEventDecorationRoute
  '/service/engagement-decoration': typeof ServiceEngagementDecorationRoute
  '/service/haldi-decoration': typeof ServiceHaldiDecorationRoute
  '/service/housewarming-decoration': typeof ServiceHousewarmingDecorationRoute
  '/service/kids-theme-decoration': typeof ServiceKidsThemeDecorationRoute
  '/service/mehendi-decoration': typeof ServiceMehendiDecorationRoute
  '/service/proposal-decoration': typeof ServiceProposalDecorationRoute
  '/service/rice-ceremony-decoration': typeof ServiceRiceCeremonyDecorationRoute
  '/service/romantic-bedroom-decoration': typeof ServiceRomanticBedroomDecorationRoute
  '/service/theme-birthday-decoration': typeof ServiceThemeBirthdayDecorationRoute
  '/service/welcome-baby-decoration': typeof ServiceWelcomeBabyDecorationRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$seoSlug'
    | '/about'
    | '/blog'
    | '/book'
    | '/contact'
    | '/mcp'
    | '/packages'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/city/$slug'
    | '/package/$id'
    | '/service/anniversary-decoration'
    | '/service/baby-shower-decoration'
    | '/service/bachelorette-decoration'
    | '/service/birthday-decoration'
    | '/service/car-boot-decoration'
    | '/service/corporate-event-decoration'
    | '/service/engagement-decoration'
    | '/service/haldi-decoration'
    | '/service/housewarming-decoration'
    | '/service/kids-theme-decoration'
    | '/service/mehendi-decoration'
    | '/service/proposal-decoration'
    | '/service/rice-ceremony-decoration'
    | '/service/romantic-bedroom-decoration'
    | '/service/theme-birthday-decoration'
    | '/service/welcome-baby-decoration'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$seoSlug'
    | '/about'
    | '/blog'
    | '/book'
    | '/contact'
    | '/mcp'
    | '/packages'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/city/$slug'
    | '/package/$id'
    | '/service/anniversary-decoration'
    | '/service/baby-shower-decoration'
    | '/service/bachelorette-decoration'
    | '/service/birthday-decoration'
    | '/service/car-boot-decoration'
    | '/service/corporate-event-decoration'
    | '/service/engagement-decoration'
    | '/service/haldi-decoration'
    | '/service/housewarming-decoration'
    | '/service/kids-theme-decoration'
    | '/service/mehendi-decoration'
    | '/service/proposal-decoration'
    | '/service/rice-ceremony-decoration'
    | '/service/romantic-bedroom-decoration'
    | '/service/theme-birthday-decoration'
    | '/service/welcome-baby-decoration'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/$seoSlug'
    | '/about'
    | '/blog'
    | '/book'
    | '/contact'
    | '/mcp'
    | '/packages'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/blog/$slug'
    | '/city/$slug'
    | '/package/$id'
    | '/service/anniversary-decoration'
    | '/service/baby-shower-decoration'
    | '/service/bachelorette-decoration'
    | '/service/birthday-decoration'
    | '/service/car-boot-decoration'
    | '/service/corporate-event-decoration'
    | '/service/engagement-decoration'
    | '/service/haldi-decoration'
    | '/service/housewarming-decoration'
    | '/service/kids-theme-decoration'
    | '/service/mehendi-decoration'
    | '/service/proposal-decoration'
    | '/service/rice-ceremony-decoration'
    | '/service/romantic-bedroom-decoration'
    | '/service/theme-birthday-decoration'
    | '/service/welcome-baby-decoration'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SeoSlugRoute: typeof SeoSlugRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  BookRoute: typeof BookRoute
  ContactRoute: typeof ContactRoute
  McpRoute: typeof McpRoute
  PackagesRoute: typeof PackagesRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CitySlugRoute: typeof CitySlugRoute
  PackageIdRoute: typeof PackageIdRoute
  ServiceAnniversaryDecorationRoute: typeof ServiceAnniversaryDecorationRoute
  ServiceBabyShowerDecorationRoute: typeof ServiceBabyShowerDecorationRoute
  ServiceBacheloretteDecorationRoute: typeof ServiceBacheloretteDecorationRoute
  ServiceBirthdayDecorationRoute: typeof ServiceBirthdayDecorationRoute
  ServiceCarBootDecorationRoute: typeof ServiceCarBootDecorationRoute
  ServiceCorporateEventDecorationRoute: typeof ServiceCorporateEventDecorationRoute
  ServiceEngagementDecorationRoute: typeof ServiceEngagementDecorationRoute
  ServiceHaldiDecorationRoute: typeof ServiceHaldiDecorationRoute
  ServiceHousewarmingDecorationRoute: typeof ServiceHousewarmingDecorationRoute
  ServiceKidsThemeDecorationRoute: typeof ServiceKidsThemeDecorationRoute
  ServiceMehendiDecorationRoute: typeof ServiceMehendiDecorationRoute
  ServiceProposalDecorationRoute: typeof ServiceProposalDecorationRoute
  ServiceRiceCeremonyDecorationRoute: typeof ServiceRiceCeremonyDecorationRoute
  ServiceRomanticBedroomDecorationRoute: typeof ServiceRomanticBedroomDecorationRoute
  ServiceThemeBirthdayDecorationRoute: typeof ServiceThemeBirthdayDecorationRoute
  ServiceWelcomeBabyDecorationRoute: typeof ServiceWelcomeBabyDecorationRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$seoSlug': {
      id: '/$seoSlug'
      path: '/$seoSlug'
      fullPath: '/$seoSlug'
      preLoaderRoute: typeof SeoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/welcome-baby-decoration': {
      id: '/service/welcome-baby-decoration'
      path: '/service/welcome-baby-decoration'
      fullPath: '/service/welcome-baby-decoration'
      preLoaderRoute: typeof ServiceWelcomeBabyDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/theme-birthday-decoration': {
      id: '/service/theme-birthday-decoration'
      path: '/service/theme-birthday-decoration'
      fullPath: '/service/theme-birthday-decoration'
      preLoaderRoute: typeof ServiceThemeBirthdayDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/romantic-bedroom-decoration': {
      id: '/service/romantic-bedroom-decoration'
      path: '/service/romantic-bedroom-decoration'
      fullPath: '/service/romantic-bedroom-decoration'
      preLoaderRoute: typeof ServiceRomanticBedroomDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/rice-ceremony-decoration': {
      id: '/service/rice-ceremony-decoration'
      path: '/service/rice-ceremony-decoration'
      fullPath: '/service/rice-ceremony-decoration'
      preLoaderRoute: typeof ServiceRiceCeremonyDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/proposal-decoration': {
      id: '/service/proposal-decoration'
      path: '/service/proposal-decoration'
      fullPath: '/service/proposal-decoration'
      preLoaderRoute: typeof ServiceProposalDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/mehendi-decoration': {
      id: '/service/mehendi-decoration'
      path: '/service/mehendi-decoration'
      fullPath: '/service/mehendi-decoration'
      preLoaderRoute: typeof ServiceMehendiDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/kids-theme-decoration': {
      id: '/service/kids-theme-decoration'
      path: '/service/kids-theme-decoration'
      fullPath: '/service/kids-theme-decoration'
      preLoaderRoute: typeof ServiceKidsThemeDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/housewarming-decoration': {
      id: '/service/housewarming-decoration'
      path: '/service/housewarming-decoration'
      fullPath: '/service/housewarming-decoration'
      preLoaderRoute: typeof ServiceHousewarmingDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/haldi-decoration': {
      id: '/service/haldi-decoration'
      path: '/service/haldi-decoration'
      fullPath: '/service/haldi-decoration'
      preLoaderRoute: typeof ServiceHaldiDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/engagement-decoration': {
      id: '/service/engagement-decoration'
      path: '/service/engagement-decoration'
      fullPath: '/service/engagement-decoration'
      preLoaderRoute: typeof ServiceEngagementDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/corporate-event-decoration': {
      id: '/service/corporate-event-decoration'
      path: '/service/corporate-event-decoration'
      fullPath: '/service/corporate-event-decoration'
      preLoaderRoute: typeof ServiceCorporateEventDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/car-boot-decoration': {
      id: '/service/car-boot-decoration'
      path: '/service/car-boot-decoration'
      fullPath: '/service/car-boot-decoration'
      preLoaderRoute: typeof ServiceCarBootDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/birthday-decoration': {
      id: '/service/birthday-decoration'
      path: '/service/birthday-decoration'
      fullPath: '/service/birthday-decoration'
      preLoaderRoute: typeof ServiceBirthdayDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/bachelorette-decoration': {
      id: '/service/bachelorette-decoration'
      path: '/service/bachelorette-decoration'
      fullPath: '/service/bachelorette-decoration'
      preLoaderRoute: typeof ServiceBacheloretteDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/baby-shower-decoration': {
      id: '/service/baby-shower-decoration'
      path: '/service/baby-shower-decoration'
      fullPath: '/service/baby-shower-decoration'
      preLoaderRoute: typeof ServiceBabyShowerDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service/anniversary-decoration': {
      id: '/service/anniversary-decoration'
      path: '/service/anniversary-decoration'
      fullPath: '/service/anniversary-decoration'
      preLoaderRoute: typeof ServiceAnniversaryDecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$id': {
      id: '/package/$id'
      path: '/package/$id'
      fullPath: '/package/$id'
      preLoaderRoute: typeof PackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/city/$slug': {
      id: '/city/$slug'
      path: '/city/$slug'
      fullPath: '/city/$slug'
      preLoaderRoute: typeof CitySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SeoSlugRoute: SeoSlugRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  BookRoute: BookRoute,
  ContactRoute: ContactRoute,
  McpRoute: McpRoute,
  PackagesRoute: PackagesRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CitySlugRoute: CitySlugRoute,
  PackageIdRoute: PackageIdRoute,
  ServiceAnniversaryDecorationRoute: ServiceAnniversaryDecorationRoute,
  ServiceBabyShowerDecorationRoute: ServiceBabyShowerDecorationRoute,
  ServiceBacheloretteDecorationRoute: ServiceBacheloretteDecorationRoute,
  ServiceBirthdayDecorationRoute: ServiceBirthdayDecorationRoute,
  ServiceCarBootDecorationRoute: ServiceCarBootDecorationRoute,
  ServiceCorporateEventDecorationRoute: ServiceCorporateEventDecorationRoute,
  ServiceEngagementDecorationRoute: ServiceEngagementDecorationRoute,
  ServiceHaldiDecorationRoute: ServiceHaldiDecorationRoute,
  ServiceHousewarmingDecorationRoute: ServiceHousewarmingDecorationRoute,
  ServiceKidsThemeDecorationRoute: ServiceKidsThemeDecorationRoute,
  ServiceMehendiDecorationRoute: ServiceMehendiDecorationRoute,
  ServiceProposalDecorationRoute: ServiceProposalDecorationRoute,
  ServiceRiceCeremonyDecorationRoute: ServiceRiceCeremonyDecorationRoute,
  ServiceRomanticBedroomDecorationRoute: ServiceRomanticBedroomDecorationRoute,
  ServiceThemeBirthdayDecorationRoute: ServiceThemeBirthdayDecorationRoute,
  ServiceWelcomeBabyDecorationRoute: ServiceWelcomeBabyDecorationRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
